#!/bin/sh
#
# Part of MariaDB Enterprise package
#
# This file is distributed as part of the SkySQL MariaDB Enterprise package.
# It is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, version 2.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Copyright 2013 (c) SkySQL Ab
#
# Author      : Massimo Siani
# Version     : 1.0
# Date        : October 2013
# Description : LSB script for Tomcat
# Note        : Script location must be: /etc/init.d  - with execute permission
# Returns     : 0 = OK - 1 = Warning
# 
# chkconfig: 2345 80 20
# description: Starts tomcat7

vTomcatBinDir=/usr/local/tomcat7/bin

fGetTomcatPid() {
    vTomcatPid=`ps -efwwww | grep tomcat | grep -v grep | awk '{print $2}'`
} 

case "$1" in

    ###################################################################################################################
    'start') 
        fGetTomcatPid           
                
        if [ "${vTomcatPid}" != "" ]; then
        
            echo "`date` - Warning: Tomcat is already running on `hostname`, process $vTomcatPid"
            vRetVal=1

        else
            ### Starting Tomcat ########################################################################################
            echo "`date` - Start: Tomcat is starting "
    
            PATH=${PATH}:/usr/sbin
    
            $vTomcatBinDir/catalina.sh start

            ### Check if the process is started ###############################################################
            sleep 1
            fGetTomcatPid
                    
            if [ "${vTomcatPid}" != "" ]; then
            
                vRetVal=0
            else
                echo "`date` - Warning: Tomcat is NOT running on `hostname`"
                vRetVal=1            
            fi
            
            ###########################################################################################################           
        fi
                
        ;;

    ###################################################################################################################
    'stop')       
        fGetTomcatPid
                
        if [ "${vTomcatPid}" != "" ]; then

            echo "`date` - Stop: Tomcat is stopping "
                        
            ### Stop Tomcat ###########################################################################################
			$vTomcatBinDir/catalina.sh stop
            ###########################################################################################################

            ### Check if the process is already running ###############################################################
			sleep 1
            fGetTomcatPid
            if [ "${vTomcatPid}" != "" ]; then
            
                $vTomcatBinDir/catalina.sh stop        
            fi                     
            ###########################################################################################################
            
            vRetVal=0
        else
            echo "`date` - Status: Tomcat is NOT running on `hostname`"
            vRetVal=0
        fi                     
        ;;

    ###################################################################################################################
    'reload'|'restart')
        $0 stop
        $0 start

        vRetVal=$?
        ;;

    ###################################################################################################################
    'status')
        fGetTomcatPid
                
        if [ "${vTomcatPid}" != "" ]; then
            echo "`date` - Status: Tomcat is running on `hostname`, process $vTomcatPid"
            vRetVal=0
        else
            echo "`date` - Status: Tomcat is NOT running on `hostname`"
            vRetVal=0
        fi
        ;;
    
    ###################################################################################################################   
    *)
        echo "Usage: Tomcat - $0 {start|stop|restart|reload|status}"

        vRetVal=1
        ;;
esac

exit $vRetVal 