#!/bin/bash

# Collect info from api.ini and manager.json, if present
/etc/mariadbmanager/update_manager_ini.sh
# WebUI key for the API
/etc/mariadbmanager/generateAPIkey.sh 1
# API scripts key for the API
/etc/mariadbmanager/generateAPIkey.sh 2
# Monitor key for the API
/etc/mariadbmanager/generateAPIkey.sh 3
# Restart the Monitor so that it reads the new key
/etc/init.d/mariadb-manager-monitor restart

# setup httpd start and restart httpd
#sed -i 's/# chkconfig: -/# chkconfig: 2345/' /etc/init.d/httpd
#rm -f /etc/rc{2,3,4,5}.d/K*httpd*
update-rc.d apache2 defaults
apachectl -k graceful

# Upgrade the API
php /var/www/restfulapi/api.php "UPGRADE"
chown -R www-data:www-data /usr/local/skysql/SQLite

# Cleanup
rm -f /etc/mariadbmanager/generateAPIkey.sh
rm -f /etc/mariadbmanager/manager_template.ini
rm -f /etc/mariadbmanager/update_manager_ini.sh
rm -f /etc/mariadbmanager/debian_site_template
